    %2019-03-08
close all;clear all;clc;
%----------------------------- 变量初始化 -----------------------------
%正真的对象参数。行代表对象，列代表对应时刻的系数。PA(0)必须等于1
PA=zeros(3,3);  
PB=zeros(3,3);

%----------------------------- 通用过程 -----------------------------
%选择项目并运行
goWork=['if(get(menuWork,''Value'')==1)'...    %执行绘制被控对象阶跃响应
    '    GPC_getStepResponse(plant_num,PA,PB);'...
    'elseif(get(menuWork,''Value'')==2)'...    %基本GPC
    '    [y,u_d]=GPC_1(plant_num,PA,PB,na,nb,N1,Nu,lambda,soft_ele,Cn);'...
    'elseif(get(menuWork,''Value'')==3)'...    %间接自适应GPC
    '    [y,u_d,Theta]=GPC_2(plant_num,PA,PB,na,nb,N1,Nu,lambda,rho,soft_ele,Cn);'...
    'elseif(get(menuWork,''Value'')==4)'...    %改进的GPC直接算法
    '    [y,u_d,Theta]=GPC_d2(plant_num,PA,PB,na,nb,N1,Nu,lambda,rho,soft_ele,Cn);'...
    'elseif(get(menuWork,''Value'')==5)'...    %简单的GPC直接算法
    '    [y,u_d,Theta]=GPC_d3(plant_num,PA,PB,na,nb,N1,Nu,lambda,soft_ele,Cn);'...
    'elseif(get(menuWork,''Value'')==6)'...    %普通的PID控制
    '    [y,u_d]=PID_simple(plant_num,PA,PB,na,nb,Kp,Ti,Td,Cn);'...
    'end'...
    ];
%绘制参数轨迹程序段（按需自己复制）
%figure;
%plot([1:?],Theta(?,:));
%grid on;
%title('参数？？？轨迹');


%获取编辑的参数
getPara=['plant_num=str2num(get(editPlantN,''String''));'...   %获取被控对象个数
    'PA(1,1)=str2num(get(editP1A1,''String''));'...  %Plant 1
    'PA(1,2)=str2num(get(editP1A2,''String''));'...
    'PA(1,3)=str2num(get(editP1A3,''String''));'...
    'PB(1,1)=str2num(get(editP1B1,''String''));'...
    'PB(1,2)=str2num(get(editP1B2,''String''));'...
    'PB(1,3)=str2num(get(editP1B3,''String''));'...
    'PA(2,1)=str2num(get(editP2A1,''String''));'...    %Plant 2
    'PA(2,2)=str2num(get(editP2A2,''String''));'...
    'PA(2,3)=str2num(get(editP2A3,''String''));'...
    'PB(2,1)=str2num(get(editP2B1,''String''));'...
    'PB(2,2)=str2num(get(editP2B2,''String''));'...
    'PB(2,3)=str2num(get(editP2B3,''String''));'...
    'PA(3,1)=str2num(get(editP3A1,''String''));'...    %Plant 3
    'PA(3,2)=str2num(get(editP3A2,''String''));'...
    'PA(3,3)=str2num(get(editP3A3,''String''));'...
    'PB(3,1)=str2num(get(editP3B1,''String''));'...
    'PB(3,2)=str2num(get(editP3B2,''String''));'...
    'PB(3,3)=str2num(get(editP3B3,''String''));'...
    'Cn=str2num(get(editNoise,''String''));'... %噪声幅度
    'na=str2num(get(editna,''String''));'...     %na nb
    'nb=str2num(get(editnb,''String''));'...
    'N1=str2num(get(editN1,''String''));'...     %N1 Nu
    'Nu=str2num(get(editNu,''String''));'...
    'lambda=str2num(get(edit_lbd,''String''));'...  %λ加权系数
    'soft_ele=str2num(get(edit_soften,''String''));'...%柔化因子
    'rho=str2num(get(edit_rho,''String''));'...  %ρ遗忘因子
    'Kp=str2num(get(editKp,''String''));'...  %PID--Kp
    'Ti=str2num(get(editTi,''String''));'...  %PID--Ti
    'Td=str2num(get(editTd,''String''));'...  %PID--Td
    ];

%更改初始化数值（界面关闭前调用）
chgEditFile=['EditData(GPCmain_edits_find(EditName,EditData,''P1A1'',''idx''))=str2num(get(editP1A1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P1A2'',''idx''))=str2num(get(editP1A2,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P1A3'',''idx''))=str2num(get(editP1A3,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P1B1'',''idx''))=str2num(get(editP1B1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P1B2'',''idx''))=str2num(get(editP1B2,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P1B3'',''idx''))=str2num(get(editP1B3,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P2A1'',''idx''))=str2num(get(editP2A1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P2A2'',''idx''))=str2num(get(editP2A2,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P2A3'',''idx''))=str2num(get(editP2A3,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P2B1'',''idx''))=str2num(get(editP2B1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P2B2'',''idx''))=str2num(get(editP2B2,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P2B3'',''idx''))=str2num(get(editP2B3,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P3A1'',''idx''))=str2num(get(editP3A1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P3A2'',''idx''))=str2num(get(editP3A2,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P3A3'',''idx''))=str2num(get(editP3A3,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P3B1'',''idx''))=str2num(get(editP3B1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P3B2'',''idx''))=str2num(get(editP3B2,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''P3B3'',''idx''))=str2num(get(editP3B3,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''PlantNum'',''idx''))=str2num(get(editPlantN,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''NoiseRange'',''idx''))=str2num(get(editNoise,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''na'',''idx''))=str2num(get(editna,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''nb'',''idx''))=str2num(get(editnb,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''N'',''idx''))=str2num(get(editN1,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''Nu'',''idx''))=str2num(get(editNu,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''lambda'',''idx''))=str2num(get(edit_lbd,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''soft_ele'',''idx''))=str2num(get(edit_soften,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''forget_ele'',''idx''))=str2num(get(edit_rho,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''Kp'',''idx''))=str2num(get(editKp,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''Ti'',''idx''))=str2num(get(editTi,''String''));'...
    'EditData(GPCmain_edits_find(EditName,EditData,''Td'',''idx''))=str2num(get(editTd,''String''));'...
    ];

%将初始化数据写入txt文件（界面关闭前调用）（不知为何出错，此段不用）
%WtxtEditFile=['EditTXT = fopen(''.\GPCmain_reset.txt'',''w'');',...
%    'EditLen = length(EditData(:));',...
%    'i=1;',...
%    'if(i<=EditLen)',...
%    '    fprintf(EditTXT,''%s\t%.4f\r\n'',EditName{i},EditData(i));',...
%    '    i=i+1;',...
%    'end',...
%    'fclose(EditTXT);'...
%    ];

%----------------------------- 界面操作 -----------------------------
%figure(1): 项目主界面，取名figGPCSim
figH=400;
figGPCSim=figure('Position',[20 60 570 figH],...
    'Name','广义预测控制仿真软件V1.0',...
    'NumberTitle','off',...   %隐藏标题栏“figure 1”这几个字
    'DeleteFcn',...  %组件删除事件
    [chgEditFile,...
    'GPCmain_wt_editTXT(EditName,EditData);',...
    ]);
%---------- 其他界面用途说明 ----------
%figure(2): 绘制被控对象阶跃响应
%figure(3)：基本GPC
%figure(4): 间接自适应GPC
%figure(5)：简单的GPC直接算法
%figure(6): 基于对象阶跃响应前N时刻估计值的GPC直接算法
%figure(7): PID控制
%=====================================

%读取参数配置文件
[EditName,EditData]=textread('.\GPCmain_reset.txt','%s%n');

%绘制被控对象面板
panelPlant=uipanel(figGPCSim,'units','pixels',...
    'Position',[15 figH-160 540 150],...
    'Title','■■1 设置被控对象');
%绘制编辑框用于提取被控对象参数信息
%绘制标签框标注必要信息
%从左到右，从上到下             %plant 1
label=uicontrol(panelPlant,'Style','text','Position',[0 110 50 20],'String','Plant 1');
label=uicontrol(panelPlant,'Style','text', 'Position',[10 90 40 20],'String','y(k)+');
editP1A1=uicontrol(panelPlant,'Style','edit','Position',[50 90 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P1A1','dat'));
label=uicontrol(panelPlant,'Style','text', 'Position',[90 90 40 20],'String','y(k-1)+');
editP1A2=uicontrol(panelPlant,'Style','edit','Position',[130 90 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P1A2','dat'));
label=uicontrol(panelPlant,'Style','text', 'Position',[170 90 40 20],'String','y(k-2)+');
editP1A3=uicontrol(panelPlant,'Style','edit','Position',[210 90 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P1A3','dat'));
label=uicontrol(panelPlant,'Style','text', 'Position',[250 90 40 20],'String','y(k-3)=');
editP1B1=uicontrol(panelPlant,'Style','edit','Position',[290 90 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P1B1','dat'));
label=uicontrol(panelPlant,'Style','text', 'Position',[330 90 40 20],'String','u(k-1)+');
editP1B2=uicontrol(panelPlant,'Style','edit','Position',[370 90 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P1B2','dat'));
label=uicontrol(panelPlant,'Style','text', 'Position',[410 90 40 20],'String','u(k-2)+');
editP1B3=uicontrol(panelPlant,'Style','edit','Position',[450 90 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P1B3','dat'));
label=uicontrol(panelPlant,'Style','text', 'Position',[490 90 40 20],'String','u(k-3)');
%plant 2
label=uicontrol(panelPlant,'Style','text','Position',[0 70 50 20],'String','Plant 2');
editP2A1=uicontrol(panelPlant,'Style','edit','Position',[50 50 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P2A1','dat'));
editP2A2=uicontrol(panelPlant,'Style','edit','Position',[130 50 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P2A2','dat'));
editP2A3=uicontrol(panelPlant,'Style','edit','Position',[210 50 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P2A3','dat'));
editP2B1=uicontrol(panelPlant,'Style','edit','Position',[290 50 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P2B1','dat'));
editP2B2=uicontrol(panelPlant,'Style','edit','Position',[370 50 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P2B2','dat'));
editP2B3=uicontrol(panelPlant,'Style','edit','Position',[450 50 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P2B3','dat'));
%plant 3
label=uicontrol(panelPlant,'Style','text','Position',[0 30 50 20],'String','Plant 3');
editP3A1=uicontrol(panelPlant,'Style','edit','Position',[50 10 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P3A1','dat'));
editP3A2=uicontrol(panelPlant,'Style','edit','Position',[130 10 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P3A2','dat'));
editP3A3=uicontrol(panelPlant,'Style','edit','Position',[210 10 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P3A3','dat'));
editP3B1=uicontrol(panelPlant,'Style','edit','Position',[290 10 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P3B1','dat'));
editP3B2=uicontrol(panelPlant,'Style','edit','Position',[370 10 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P3B2','dat'));
editP3B3=uicontrol(panelPlant,'Style','edit','Position',[450 10 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'P3B3','dat'));
%需要前几段被控对象
label=uicontrol(panelPlant,'Style','text','Position',[160 110 150 20],'String','■需几段(0~?)被控对象仿真：');
editPlantN=uicontrol(panelPlant,'Style','edit','Position',[310 112 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'PlantNum','dat'));
%噪声幅度+-Cn
label=uicontrol(panelPlant,'Style','text','Position',[370 110 90 20],'String','■噪声幅度(±?)：');
editNoise=uicontrol(panelPlant,'Style','edit','Position',[460 112 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'NoiseRange','dat'));


%na、nb面板
panel_nanb=uipanel(figGPCSim,'units','pixels',...
    'Position',[15 figH-210 280 45],...
    'Title','■■2 被控对象模型的多项式的相关系数');
label=uicontrol(panel_nanb,'Style','text','Position',[0 5 100 20],...
    'String','■na(≥y项阶数):');
editna=uicontrol(panel_nanb,'Style','edit','Position',[100 5 20 20],...
    'String',GPCmain_edits_find(EditName,EditData,'na','dat'));
label=uicontrol(panel_nanb,'Style','text','Position',[130 5 120 20],...
    'String','■nb(≥u阶数-1且＞0):');
editnb=uicontrol(panel_nanb,'Style','edit','Position',[250 5 20 20],...
    'String',GPCmain_edits_find(EditName,EditData,'nb','dat'));

%N1,Nu,面板
panel_N_Lbd=uipanel(figGPCSim,'units','pixels',...
    'Position',[15 figH-260 280 45],...
    'Title','■■3 GPC基本参数  N≥Nu＞0');
label=uicontrol(panel_N_Lbd,'Style','text','Position',[0 5 100 20],...
    'String','■最大预测时域N:');
editN1=uicontrol(panel_N_Lbd,'Style','edit','Position',[100 5 20 20],...
    'String',GPCmain_edits_find(EditName,EditData,'N','dat'));
label=uicontrol(panel_N_Lbd,'Style','text','Position',[140 5 80 20],...
    'String','■控制时域Nu:');
editNu=uicontrol(panel_N_Lbd,'Style','edit','Position',[220 5 20 20],...
    'String',GPCmain_edits_find(EditName,EditData,'Nu','dat'));

%加权系数λ
label=uicontrol(figGPCSim,'Style','text','Position',[10 figH-290 100 20],...
    'String','■■4 加权系数λ:');
edit_lbd=uicontrol(figGPCSim,'Style','edit','Position',[110 figH-290 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'lambda','dat'));

%柔化因子α（(1-α)为设定值的权重，α为每级柔化值的权重）
label=uicontrol(figGPCSim,'Style','text','Position',[155 figH-290 100 20],...
    'String','■■5 柔化因子α:');
edit_soften=uicontrol(figGPCSim,'Style','edit','Position',[255 figH-290 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'soft_ele','dat'));

%遗忘因子ρ
label=uicontrol(figGPCSim,'Style','text','Position',[10 figH-320 100 20],...
    'String','■■6 遗忘因子ρ:');
edit_rho=uicontrol(figGPCSim,'Style','edit','Position',[110 figH-320 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'forget_ele','dat'));

%PID面板（用于效果比较）
panel_PID=uipanel(figGPCSim,'units','pixels',...
    'Position',[15 figH-370 280 45],...
    'Title','■■7 PID参数 (Ki=Kp/Ti, Kd=Kp*Td)');
label=uicontrol(panel_PID,'Style','text','Position',[0 5 30 20],...
    'String','Kp:');
editKp=uicontrol(panel_PID,'Style','edit','Position',[30 5 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'Kp','dat'));
label=uicontrol(panel_PID,'Style','text','Position',[80 5 30 20],...
    'String','Ti');
editTi=uicontrol(panel_PID,'Style','edit','Position',[110 5 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'Ti','dat'));    %Ti>65535时等于正无穷，不存在i项
label=uicontrol(panel_PID,'Style','text','Position',[160 5 30 20],...
    'String','Td:');
editTd=uicontrol(panel_PID,'Style','edit','Position',[190 5 40 20],...
    'String',GPCmain_edits_find(EditName,EditData,'Td','dat'));



%仿真项目菜单
label=uicontrol(figGPCSim,'Style','text','Position',[380 figH-190 120 20],'String','●请选择仿真的项目');
menuWork=uicontrol(figGPCSim,...   %gcf不知是什么
    'Style','popupmenu',...
    'Position',[380 figH-210 175 20],...
    'String','●被控对象阶跃响应（需配置面板■■1）|●基本的GPC（面板■■1 2 3 4 5）|●间接自适应GPC（■■1 ~ 6）|●基于对象阶跃响应前N个估计值的GPC直接算法（■■1~6）|●简单的GPC直接算法（■■1 ~ 5）|●普通PID控制（■■1、7）',...
    'Value',1);
%运行按钮
pushbutRun=uicontrol(figGPCSim,...
    'Style','pushbutton',...
    'Position',[380 figH-260 175 40],...
    'String','运    行',...
    'CallBack',...
    [getPara,...                   %获取被控对象参数
    goWork,...
    ]);
